config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :ramen_shops
  get 'records/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ramen_shop.rb
class RamenShop < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :ramen_shop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ramen_shops_controller.rb
class RamenShopsController < ApplicationController
  before_action :set_ramen_shop, only: %i[ show edit update destroy ]

  # GET /ramen_shops or /ramen_shops.json
  def index
    @ramen_shops = RamenShop.all

    respond_to do |format|
      format.html 
      format.json { render json: @ramen_shops } 
    end
  end

  # GET /ramen_shops/1 or /ramen_shops/1.json
  def show
  end

  # GET /ramen_shops/new
  def new
    @ramen_shop = RamenShop.new
  end

  # GET /ramen_shops/1/edit
  def edit
  end

  # POST /ramen_shops or /ramen_shops.json
  def create
    @ramen_shop = RamenShop.new(ramen_shop_params)

    respond_to do |format|
      if @ramen_shop.save
        format.html { redirect_to ramen_shop_url(@ramen_shop), notice: "Ramen shop was successfully created." }
        format.json { render :show, status: :created, location: @ramen_shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ramen_shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ramen_shops/1 or /ramen_shops/1.json
  def update
    respond_to do |format|
      if @ramen_shop.update(ramen_shop_params)
        format.html { redirect_to ramen_shop_url(@ramen_shop), notice: "Ramen shop was successfully updated." }
        format.json { render :show, status: :ok, location: @ramen_shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ramen_shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ramen_shops/1 or /ramen_shops/1.json
  def destroy
    @ramen_shop.destroy

    respond_to do |format|
      format.html { redirect_to ramen_shops_url, notice: "Ramen shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ramen_shop
      @ramen_shop = RamenShop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ramen_shop_params
      params.require(:ramen_shop).permit(:name, :address, :plate)
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def create
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @ramen_shops = RamenShop.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ramen_shops_helper.rb
module RamenShopsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTyakudon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
      <%= yield(:js) %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ramen_shops/_form.html.erb
<%= form_with(model: ramen_shop) do |form| %>
  <% if ramen_shop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ramen_shop.errors.count, "error") %> prohibited this ramen_shop from being saved:</h2>

      <ul>
        <% ramen_shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :plate, style: "display: block" %>
    <%= form.text_field :plate %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ramen_shops/_ramen_shop.html.erb
<% content_for :js do %>
  <%= javascript_import_module_tag "timer" %>
<% end %>

<div id="<%= dom_id ramen_shop %>">
  <p>
    <strong>Name:</strong>
    <%= ramen_shop.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= ramen_shop.address %>
  </p>
  <div id="container">
    <div id="time">00:00:00.000</div>
    <div id="buttons">
      <input id="start" type="button" value="接続！">
      <input id="stop" type="button" value="休憩" disabled="true">
      <input id="end" type="button" value="着丼！" disabled="true">
      <input id="reset" type="button" value="はじめから" disabled="true">
      <input id="retire" type="button" value="離脱" disabled="true">
    </div>
  </div>  
</div>

app/views/ramen_shops/edit.html.erb
<h1>Editing ramen shop</h1>

<%= render "form", ramen_shop: @ramen_shop %>

<br>

<div>
  <%= link_to "Show this ramen shop", @ramen_shop %> |
  <%= link_to "Back to ramen shops", ramen_shops_path %>
</div>

app/views/ramen_shops/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ramen shops</h1>

<div id="ramen_shops">
  <% @ramen_shops.each do |ramen_shop| %>
    <%= render ramen_shop %>
    <p>
      <%= link_to "Show this ramen shop", ramen_shop %>
    </p>
  <% end %>
</div>

<%= link_to "New ramen shop", new_ramen_shop_path %>

app/views/ramen_shops/new.html.erb
<h1>New ramen shop</h1>

<%= render "form", ramen_shop: @ramen_shop %>

<br>

<div>
  <%= link_to "Back to ramen shops", ramen_shops_path %>
</div>

app/views/ramen_shops/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @ramen_shop %>

<!-- Googleマップ表示エリア(地図を表示) -->
<div id="map" style="width:620px; height:400px"></div>
<div>
  <%= link_to "Back to ramen shops", ramen_shops_path %>
</div>

<!-- Googleマップ表示用の Javascript -->
<script>
  function initMap(){
    // 地図の位置情報(緯度・経度)を取得
    let mapPosition = {lat: <%= @ramen_shop.latitude || 0 %> , lng: <%= @ramen_shop.longitude || 0 %> };
    let map = new google.maps.Map(document.getElementById('map'), {
      zoom: 17,
      center: mapPosition
    });
    let transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);
    
    let contentString = '【住所】<%= @ramen_shop.address %>';
    let infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    
    let marker = new google.maps.Marker({
      position: mapPosition,
      map: map,
      title: contentString
    });
    
    marker.addListener('click', function(){
      infowindow.open(map, marker);
    });
  }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

app/views/records/create.html.erb
<h1>Records#create</h1>
<p>Find me in app/views/records/create.html.erb</p>

app/views/welcome/index.html.erb
<h1>ラーメン店舗一覧</h1>
<ul>
  <% @ramen_shops.each do |shop| %>
    <li>
      <%= shop.name %>
      <%= link_to '時間計測', ramen_shop_path(shop) %>
    </li>
  <% end %>
</ul>

<!-- Googleマップ表示エリア(地図を表示) -->
<div id="map" style="width:620px; height:400px"></div>
<!-- Googleマップ表示用の Javascript -->
<script>
  function initMap() {
    // 現在地の緯度経度情報を取得
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var currentLocation = {
          // lat: position.coords.latitude,
          // lng: position.coords.longitude
          lat: 35.7000396,
          lng: 139.7752222
        };
        // Google Maps APIを使用して地図を表示
        var map = new google.maps.Map(document.getElementById('map'), {
          center: currentLocation,
          zoom: 18
        });
        // DBから店舗情報を取得
        fetch('/ramen_shops.json')
          .then(function(response) {
            return response.json();
          })
          .then(function(data) {
            // 距離計算
            for (var i = 0; i < data.length; i++) {
              var shopLocation = {
                lat: data[i].latitude,
                lng: data[i].longitude
              };
              var distance = getDistance(currentLocation, shopLocation);
              // 距離が100m以内の場合、マーカーを地図上に表示
              if (distance <= 500) {
                var marker = new google.maps.Marker({
                  position: shopLocation,
                  map: map,
                  title: data[i].name
                });
                // マーカーがクリックされたときの処理
                google.maps.event.addListener(marker, 'click', (function(data){
                  return function(){
                    window.location.href = "/ramen_shops/" + data.id; 
                  };
                })(data[i]));
              }
            }
          })
          .catch(function() {
            alert("Failed to load shops.");
          });
      }, function() {
        alert("Failed to get current location.");
      });
    } else {
      alert("Geolocation is not supported by this browser.");
    }
  }

  // 2点間の距離を計算する関数
  function getDistance(start, end) {
    var R = 6371; // 地球の半径（km）
    var dLat = (end.lat - start.lat) * Math.PI / 180;
    var dLon = (end.lng - start.lng) * Math.PI / 180;
    var a = Math.sin(dLat/2) * Math.sin(dLat/2) + Math.cos(start.lat * Math.PI / 180) * Math.cos(end.lat * Math.PI / 180) * Math.sin(dLon/2) * Math.sin(dLon/2);
    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    var d = R * c; // 2点間の距離（km）
    var distance = d * 1000; // kmからmに変換
    return distance;
  }
</script> 
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>